#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Temporarily unset an ENV VAR for a `command`
# Source: https://unix.stackexchange.com/a/388852
# Example: `uenv GIT_EDITOR git commit`
function uenv() {
  local "$1" # $1 variable declared as initially unset in bash¹
  shift
  "$@"
}
